vyatkina_a_electric_homepage:
    path:     /
    defaults: { _controller: VyatkinaAElectricBundle:Default:index }

vyatkina_a_electric_check:
    path:     /check
    defaults: { _controller: VyatkinaAElectricBundle:Default:check }
    methods: [POST]

vyatkina_a_electric_joker:
    path:     /joker
    defaults: { _controller: VyatkinaAElectricBundle:Default:joker }
    methods: [POST]

vyatkina_a_electric_save:
    path:     /save
    defaults: { _controller: VyatkinaAElectricBundle:Default:save }
    methods: [POST]
